name: release

on:
  push:
    branches:
      - main

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}

    steps:
      - name: release-please
        id: release
        uses: googleapis/release-please-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node

  release-assets:
    needs: release-please
    runs-on: ubuntu-latest
    if: ${{ needs.release-please.outputs.release_created }}
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          cache: pnpm
          node-version: latest

      - name: install dependencies
        run: pnpm install

      - name: build
        run: pnpm build

      - name: publish gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          force_orphan: true
          cname: d.metacubex.one
          commit_message: ${{ needs.release-please.outputs.tag_name }}

      - name: compress dist
        run: tar czvf compressed-dist.tgz -C dist .

      - name: attach github release artifacts
        uses: softprops/action-gh-release@v2
        with:
          files: compressed-dist.tgz
          tag_name: ${{ needs.release-please.outputs.tag_name }}
